language: ruby
sudo: false
before_install:
  - rm Gemfile.lock
  - gem update --system
script:
  - cd test/dummy && bin/rails db:create db:migrate
  - cd ../.. && bin/test
env:
  - RAILS=5.2
rvm:
  - 2.6.0
  - 2.7.0
matrix:
  fast_finish: true
services:
  - postgresql
notifications:
  email: false
